user_num1, user_num2 = input("Enter two numbers of your choice for computational tasks: ").split()
add = int(user_num1) + int(user_num2)
sub = add = int(user_num2) - int(user_num1)
mul = add = int(user_num1) * int(user_num2)
divi = add = int(user_num1) // int(user_num2)
print(f" Computational Results for user choice of numbers==== \n Addition: {add} \n Subtraction: {sub} \n Multiplication: {mul} \n Division: {divi}  ")
